name: Deploy AWS dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy AWS dev
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials from dev account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::938347404652:role/moneytracker-cdk-cloudformation
        aws-region: eu-central-1
    - name: Install CDK
      run: npm install -g aws-cdk
    - name: Synthesize CloudFormation stack
      run: cdk synth
    - name: Bootstrap CDK environment
      run: cdk bootstrap
    - name: Deploy to AWS dev
      run: cdk deploy
